package com.ppp.currencyexchange.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryLight = Color(0xFF1A73E8)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFD3E3FD)
val OnPrimaryContainerLight = Color(0xFF041E49)
val SecondaryLight = Color(0xFF5F6368)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFE8EAED)
val OnSecondaryContainerLight = Color(0xFF1F1F1F)
val BackgroundLight = Color(0xFFFFFFFF)
val OnBackgroundLight = Color(0xFF1F1F1F)
val SurfaceLight = Color(0xFFFFFFFF)
val OnSurfaceLight = Color(0xFF1F1F1F)
val SurfaceVariantLight = Color(0xFFF1F3F4)
val OnSurfaceVariantLight = Color(0xFF444746)
val ErrorLight = Color(0xFFD93025)
val OnErrorLight = Color(0xFFFFFFFF)
val OutlineLight = Color(0xFFDADCE0)

val PrimaryDark = Color(0xFF8AB4F8)
val OnPrimaryDark = Color(0xFF062E6F)
val PrimaryContainerDark = Color(0xFF0842A0)
val OnPrimaryContainerDark = Color(0xFFD3E3FD)
val SecondaryDark = Color(0xFFC4C7C5)
val OnSecondaryDark = Color(0xFF303134)
val SecondaryContainerDark = Color(0xFF3C4043)
val OnSecondaryContainerDark = Color(0xFFE8EAED)
val BackgroundDark = Color(0xFF1F1F1F)
val OnBackgroundDark = Color(0xFFE8EAED)
val SurfaceDark = Color(0xFF1F1F1F)
val OnSurfaceDark = Color(0xFFE8EAED)
val SurfaceVariantDark = Color(0xFF303134)
val OnSurfaceVariantDark = Color(0xFFC4C7C5)
val ErrorDark = Color(0xFFF28B82)
val OnErrorDark = Color(0xFF601410)
val OutlineDark = Color(0xFF5F6368)

val OnlineGreen = Color(0xFF34A853)
val OnlineGreenDark = Color(0xFF81C995)
val OfflineOrange = Color(0xFFFA8B1F)
val OfflineOrangeDark = Color(0xFFFDB663)
val FavoriteGold = Color(0xFFFFC107)
